#!/bin/bash
#
# qemu-ifup is a script that will configure bridge networking for the KVM
#

set -eu

BR_INTERFACE="br-qemu"
TAP_INTERFACE="tap0"
ETH_INTERFACE="eth0"

# create bridge
brctl addbr ${BR_INTERFACE}

# link bridge with tap and eth interfaces
brctl addif ${BR_INTERFACE} ${TAP_INTERFACE}
ip addr flush dev ${ETH_INTERFACE}
brctl addif ${BR_INTERFACE} ${ETH_INTERFACE}

# set all interafaces 'up'
ip link set ${TAP_INTERFACE} up
ip link set ${BR_INTERFACE} up
ip link set ${ETH_INTERFACE} up
