version: 2.1

orbs:
  architect: giantswarm/architect@0.9.0

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/k8s-kvm"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/k8s-kvm"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          filters:
            tags:
              ignore: /^v.*/