version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/
